#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
RASI="$HOME/.config/rofi/deathemonic/config/launcher.rasi"

# Run
rofi \
    -show drun \
	-theme ${RASI}
